[package]
name = "modbus_experiment"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.44.0", features = ["full"] }
tokio-modbus = { version = "0.16.1", features = ["rtu", "rtu-server"] }
tokio-serial = "5.4.5"
